import React from 'react'

function About() {
  return (
    <>
      <div>About</div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi diam felis, egestas sit amet sagittis et, volutpat non quam. Donec congue nisl quis pharetra congue. Etiam a velit at ipsum ullamcorper imperdiet in sit amet felis. Integer vitae eleifend lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed justo massa, tempor non ex ac, blandit cursus felis. Vivamus eu mi at eros posuere dictum. Nam iaculis tempor erat, facilisis mollis lacus consectetur vel. Integer pharetra quis dolor quis varius. Etiam ut nisi suscipit, accumsan ex vel, tincidunt lorem.</p>
      <p>Praesent tincidunt, dui et ullamcorper ullamcorper, orci orci pellentesque lorem, non dapibus odio leo efficitur lorem. Praesent nec efficitur lorem. Nullam tincidunt, ipsum eu lacinia vehicula, magna enim vulputate nisl, ac tincidunt eros ex at odio. Phasellus a orci volutpat, molestie tellus ut, lobortis leo. Maecenas vulputate elit vulputate lacus vehicula convallis. Donec quam magna, aliquet ut nisi vel, volutpat tristique lectus. Vivamus eu laoreet sapien, ac congue velit. Duis semper vestibulum dolor, quis dictum metus consequat sollicitudin. Proin feugiat volutpat laoreet. Mauris interdum odio at justo tincidunt, placerat tincidunt elit pulvinar. Vestibulum eu volutpat nisl, ac tincidunt nisl. Integer a nulla elementum lorem ultricies porttitor ut vel est.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi diam felis, egestas sit amet sagittis et, volutpat non quam. Donec congue nisl quis pharetra congue. Etiam a velit at ipsum ullamcorper imperdiet in sit amet felis. Integer vitae eleifend lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed justo massa, tempor non ex ac, blandit cursus felis. Vivamus eu mi at eros posuere dictum. Nam iaculis tempor erat, facilisis mollis lacus consectetur vel. Integer pharetra quis dolor quis varius. Etiam ut nisi suscipit, accumsan ex vel, tincidunt lorem. Praesent tincidunt, dui et ullamcorper ullamcorper, orci orci pellentesque lorem, non dapibus odio leo efficitur lorem. Praesent nec efficitur lorem. Nullam tincidunt, ipsum eu lacinia vehicula, magna enim vulputate nisl, ac tincidunt eros ex at odio. Phasellus a orci volutpat, molestie tellus ut, lobortis leo. Maecenas vulputate elit vulputate lacus vehicula convallis. Donec quam magna, aliquet ut nisi vel, volutpat tristique lectus. Vivamus eu laoreet sapien, ac congue velit. Duis semper vestibulum dolor, quis dictum metus consequat sollicitudin. Proin feugiat volutpat laoreet. Mauris interdum odio at justo tincidunt, placerat tincidunt elit pulvinar. Vestibulum eu volutpat nisl, ac tincidunt nisl. Integer a nulla elementum lorem ultricies porttitor ut vel est.</p>
    </>
  )
}

export default About